### ISSUE TITLE
Pre Pull Request :-) 'Preelaborate' Packages.

### ISSUE THREAD

**Issue by danieagle** [jrcarter/PragmARC#15]
Hi J.R Carter!

Pleaaase you can see the changes in 
repo => https://github.com/danieagle/PragmARC ?

branches:

Gnat-13 => fixed b_strings to allow PragmARC compile. 
preelaborate01 => packages changed to use Ada Preelaborate. I Will Use It in
 an pure/preelaborate environment. the changes are trivial but very important to me.

God Bless You,
GrateFull,
Dani.

**Comment by jrcarter** [comment]
B_Strings is valid Ada 12. GNAT 13 introduced an error which rejected it ([110488](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=110488)). This is resolved in GNAT 13.3 and later.

My policy is not to work around compiler errors, so I will not be changing this. I recommend only using compilers without significant errors. If you need to use a compiler with significant errors you are free to modify the package to work around your compiler's errors. Note that with your changes the comment about the default initial value of a B_String is no longer correct, as it now implies a specific discriminant.

Adding Preelaborate to PragmARC.Matching.Regular_Expression is trivial and I will make the change in the near future. Until then, you will want to use your version of the package.

**Comment by jrcarter** [comment]
Preelaborate added to PragmARC.Matching.Regular_Expression in commit b274d72

**Comment by danieagle** [comment]
Hi Carter! Very Very Very Thanks by Your Hard Work and Care! 

I changed more 4 packages in preelaborate01 and uploaded it now :-)

https://github.com/danieagle/PragmARC/blob/preelaborate01/pragmarc-unbounded_numbers-integers.ads
https://github.com/danieagle/PragmARC/blob/preelaborate01/pragmarc-unbounded_numbers-integers.adb

https://github.com/danieagle/PragmARC/blob/preelaborate01/pragmarc-unbounded_numbers-rationals.ads
https://github.com/danieagle/PragmARC/blob/preelaborate01/pragmarc-unbounded_numbers-rationals.adb

The Changes are _really trivial_ and important to me. 

Obs: update first pragmarc-unbounded_numbers-integers.ad{s,b}

God and Mary Blesses You!
GrateFull,
Dani. :-D

**Comment by jrcarter** [comment]
> https://github.com/danieagle/PragmARC/blob/preelaborate01/pragmarc-unbounded_numbers-integers.ads
https://github.com/danieagle/PragmARC/blob/preelaborate01/pragmarc-unbounded_numbers-integers.adb
https://github.com/danieagle/PragmARC/blob/preelaborate01/pragmarc-unbounded_numbers-rationals.ads
https://github.com/danieagle/PragmARC/blob/preelaborate01/pragmarc-unbounded_numbers-rationals.adb

It is not necessary to add Preelaborate to the body of a package that has it on the spec.

I will get to this shortly. Until then I am reopening this issue.

**Comment by jrcarter** [comment]
Sorry, I should have looked more closely at what this entailed. These are general-purpose components, and in general users do not need Preelaborate. When the change is simply adding the aspect, it doesn't have any negative effect on the general user.

However, these changes involve changing constants to functions, and I'm not going to do that to general users. As you have special requirements that these general-purpose components don't meet, you should continue as you have been and use your versions that do meet your requirements.
