### ISSUE TITLE
(Whishlist) threefish-1024

### ISSUE THREAD

**Issue by danieagle** [jrcarter/PragmARC#7]
Hi!

  Do you can create a 1024 bits of Threefish ? or accept a code contribution ?

  Thanks!

  Happy New Year!
  Best Whishes,
  Dani.

**Comment by jrcarter** [comment]
Of course 512- and 1024-bit versions are possible. What appeals to me about the 256-bit version is the simplicity and elegance of the specification and implementation. The larger block sizes are more complex and implementations would be less clear.

I also don't see that there is a significant advantage to using a larger block size rather than encrypting multiple smaller blocks, but maybe there is something I'm missing.

If you have, or wish to create, implementations of Threefish with larger block sizes, I would be happy to consider them for inclusion. Be sure to strictly follow the [coding standard](https://github.com/jrcarter/Coding_Standard). If there is going to be a 1024-bit version there should also be a 512-bit version.

**Comment by danieagle** [comment]
Thanks!

A larger block size is great for me because I'm in a project using postquantum crypto kem + crypto symmetric.
Why? In an age of quantum computers, all symmetric algorithms lose half their strength. threefish is knowned by this strengh but there are some attacks against It , none them feasible, than half the strengh of threefish.  By choosing 1024 bit block
I want be a future proof surviver o two halfs o the strength of threefish.

Thanks!
Best Whishes,
Dani.

**Comment by danieagle** [comment]
Hi!

Created using Theefish_256 as model, Threefish_512 and Threefish_1024.
I Need some test vectors to test better.

Thanks!
Best Whishes,
Dani.

[https://github.com/danieagle/PragmARC/tree/threefish_512](url)

**Comment by jrcarter** [comment]
The test cases for Threefish are given in the Readme for Encryption_Utilities (https://github.com/jrcarter/Encryption-utilities).

These look good. You need to update the comments and do a better job of aligning things, such as in Rot and Permute.

**Comment by danieagle** [comment]
Hi!

I'll update him.

Thanks,
Best Whishes,
Dani.

**Comment by danieagle** [comment]
Hi!

Do the rot in 1024bit version need a new layout ?
Updated.

Thanks,
Best Whishes,
Dani.

**Comment by jrcarter** [comment]
The alignment of Rot and Permute looks good in both versions. The declarations in Permute should have excess spaces removed: `Temp0 : ...`

The return aggregates for the "+" and "-" functions should also have things lined up.

Where you have `(0  ..  1)` (2 spaces before and after `..`) lined up with `(10 .. 11)`, it should be `( 0 ..  1)`. Numbers are aligned on the 1s column.

The copyright needs to be updated to the current year.

The name format for the history comments is First-initial Last-name. With Norte de Moraes as your last name, you'll have to move all the `Vx.y--` comments over to line up. Where you have `Xbits` (X in 512 | 1024) you need a hyphen: `X-bits`.

**Comment by danieagle** [comment]
hi!

Updated.

Thanks,
Best Whishes,
Dani.

**Comment by jrcarter** [comment]
These look pretty good now. Have you tested them against the test cases? You should do that, and provide the test programs (similar to Tf_Test) to me for inclusion in the Encryption-utilities (https://github.com/jrcarter/Encryption-utilities).

**Comment by danieagle** [comment]
Hi!

Thanks!

I'll create the tests now.

one doubt: the values in [https://github.com/bmalkow/java-bc-threefish](url) are in a string form ? or are raw 16bit numbers ?

Thanks,
Best Whishes,
Dani.

**Comment by jrcarter** [comment]
Good question. The expected outputs for the 256-bit test cases in that Readme are wrong. You can find the correct ones in Tf_Test, and in https://github.com/bmalkow/java-bc-threefish/blob/master/test/org/bouncycastle/crypto/test/ThreefishTest.java. IIRC, I used the cases from the other link, which seems to no longer exist. I presume the test cases given in that Java file for the 512- and 1024-bit versions are also correct. Tf_Test shows how to translate these into Byte_Lists.

**Comment by danieagle** [comment]
Hi!

Fully working now.

Thanks!,
Best Whishes,
Dani.

obs: was added tf_test_512 and tf_test_1024 in https://github.com/danieagle/Encryption-utilities/tree/test_512_10124
Enjoy!

**Comment by jrcarter** [comment]
Great. I will probably rename things, and move common declarations into a common root pkg, before releasing.

**Comment by danieagle** [comment]
Hi!

Ok!

Thanks,
Best Whishes,
Dani.

**Comment by jrcarter** [comment]
If forgot to close this after I added the new versions to the repo.
