### ISSUE TITLE
(WhishList) Dilithium5 pqc sign, Kyber1024 pqc key encapsulation mechanism and BLAKE3 in pure Ada

### ISSUE THREAD

**Issue by danieagle** [jrcarter/PragmARC#9]
Hi Carter!
You Fine? I'm Fine too.

The Dilithium and Kyber are choosen by NIST Champions in his PostQuantum Cryptograph Competition [NIST link](https://csrc.nist.gov/Projects/post-quantum-cryptography/selected-algorithms-2022)

Blake3 is a Cryptograph hash.

I Believe Dilithium and Kyber, to a great extent, _will_ become a must for many developers and applications.
I am particularly interested in Dilithium5 and Kyber1024 versions, but failed in creating a pure Ada versions from the papers.

Pleeease Carter, can you create Ada versions of Kyber1024 and Dilithium5? and toast me and the Ada Community with your achievement?

Very Very Very Thanks!

Best Whishes,
GrateFull, Dani.

[Kyber and Dilithium Home](https://pq-crystals.org/index.shtml)
[Kyber Git](https://github.com/pq-crystals/kyber)
[Dilithium Git](https://github.com/pq-crystals/dilithium)
[PQClean](https://github.com/PQClean/PQClean)

p.s.: The PQClean sign versions, has  two options to use just the sign part without prepend the data signed.

**Comment by jrcarter** [comment]
What difficulties did you encounter?

**Comment by danieagle** [comment]
Hi Carter!

  I simply no longer remember all the formulas, calculations and mathematical 
symbols used in these papers. :-D
  I can create binds from C versions, but this is more a hack than a permanent solution,
and after of long long time seeing your work with Ada, 
I'm feeling You are The Person(TM) to create these Ada versions.

 I can help maintain update and improve  the versions than you'll do, 
but I had no success trying to create Ada versions from scratch.

Very Very Very Thanks!!!

Best Whishes,
GrateFull, Dani.

**Comment by jrcarter** [comment]
Can you provide direct links to descriptions of the algorithms? I am not able to understand the mathematics in the links you supplied.

**Comment by danieagle** [comment]
Hi Carter!

Very Very Very Thanks!!!!!!!!

[kyber.pdf](https://github.com/jrcarter/PragmARC/files/10665324/kyber.pdf)

[dilithium_nist.pdf](https://github.com/jrcarter/PragmARC/files/10665346/dilithium_nist.pdf)

[blake3.pdf](https://github.com/BLAKE3-team/BLAKE3-specs/blob/master/blake3.pdf)

Very Very Very Thanks Again!!!!!!!!!!!!!!!

Best Whishes,
GrateFull, Dani.

**Comment by jrcarter** [comment]
I'm afraid the description of Kyber loses me in the second paragraph of section 1.1.

**Comment by danieagle** [comment]
Thanks :-D

I'll consider this closed.

Best Wishes,
GrateFull Dani.

**Comment by jrcarter** [comment]
Kyber, now known as ML-KEM, now has a SPARK implementation at [awslabs](https://github.com/awslabs/LibMLKEM) that may be of interest to you.

**Comment by danieagle** [comment]
Thanks!

-- 
 Enviado com Tuta; aproveite e-mails seguros e sem anúncios: 
 https://tuta.com 


16 de fev. de 2024, 07:36 por ***@***.***:
